Migrate away from docker (#300)
* Migrate away from docker
* scan when there is a baseline
* add fake secret to test action
* add diff to break the build
* remove test file. detect-secret workflow should pass now
* cleanup workflow

diff --git a/.github/workflows/detect-secrets.yml b/.github/workflows/detect-secrets.yml
--- a/.github/workflows/detect-secrets.yml
+++ b/.github/workflows/detect-secrets.yml
@@ -16,12 +16,48 @@ jobs:
         disable-telemetry: true
         allowed-endpoints: >
           detect-secrets-client-version.s3.us-south.cloud-object-storage.appdomain.cloud:443
+          files.pythonhosted.org:443
           github.com:443
+          pypi.org:443
 
     - name: Checkout
       uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
       with:
         fetch-depth: 0
 
-    - name: Run IBM's detect-secrets
-      uses: tomwillis608/detect-secrets-action@34a10e193e04c8b70e8ce781bb3312c6b9b73b9c # v2.1.2
+    - name: Setup Python
+      uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4
+      with:
+        python-version: "3.7"
+
+    - name: "Install dev dependencies"
+      run: |
+        pip install --upgrade pip
+        pip install --use-pep517 --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
+        pip install --no-cache-dir certifi>=2022.12.7 --upgrade
+        sudo apt-get install -y jq
+
+    - name: "Run detect-secrets"
+      run: |
+        set -o pipefail
+        set -exu
+        DS_REQUIRE_BASELINE=1
+        DS_BASELINE_FILE="./.secrets.baseline"
+        detect-secrets --version
+        if [ ! -r "$DS_BASELINE_FILE" ]; then
+          if [ "$DS_REQUIRE_BASELINE" -eq 0 ]; then
+            detect-secrets -v scan >"$DS_BASELINE_FILE"
+          else
+            echo "No readable detect-secrets baseline file found at '$DS_BASELINE_FILE', and it was set to required by \$DS_REQUIRE_BASELINE ($DS_REQUIRE_BASELINE)"
+            exit 255
+          fi
+        else
+          cp .secrets.baseline .secrets.new
+          detect-secrets scan --update .secrets.new
+          # if there is any difference between the known and newly detected secrets, break the build
+          list_secrets() { jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort; }
+          if ! diff <(list_secrets .secrets.baseline) <(list_secrets .secrets.new) >&2; then
+            echo "Detected new secrets in the repo" >&2
+            exit 1
+          fi
+        fi
